import a_frog from './animals/a_frog.png';
import ab_ghost from './animals/ab_ghost.png';
import b_bee from './animals/b_bee.png';
import c_teddy from './animals/c_teddy.png';
import d_chick from './animals/d_chick.png';
import e_octopus from './animals/e_octopus.png';
import f_rabbit from './animals/f_rabbit.png';
import g_rabbit from './animals/g_rabbit.png';
import h_rabbit from './animals/h_rabbit.png';
import i_fish from './animals/i_fish.png';
import j_chick from './animals/j_chick.png';
import k_teddy from './animals/k_teddy.png';
import l_cat from './animals/l_cat.png';
import m_dino from './animals/m_dino.png';
import n_chick from './animals/n_chick.png';
import o_rabbit from './animals/o_rabbit.png';
import p_chick from './animals/p_chick.png';
import q_rabbit from './animals/q_rabbit.png';
import r_rabbit from './animals/r_rabbit.png';
import s_stingray from './animals/s_stingray.png';
import t_chick from './animals/t_chick.png';
import u_mouse from './animals/u_mouse.png';
import v_octopus from './animals/v_octopus.png';
import w_cow from './animals/w_cow.png';
import x_penguin from './animals/x_penguin.png';
import y_octopus from './animals/y_octopus.png';
import z_octopus from './animals/z_octopus.png';

export const animals = [
    {
        img: a_frog,
        name: 'Frăguța',
        price: null,
        description: 'Frăguța este o broscuță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'a_frog',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: b_bee,
        name: 'Bulina',
        price: null,
        description: 'Bulina este o albinuță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'b_bee',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: ab_ghost,
        name: 'Mița',
        price: null,
        description: 'Mița este o fantomiță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'ab_ghost',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: true,
    },
    {
        img: c_teddy,
        name: 'Mitică',
        price: null,
        description: 'Mitică este un ursuleț croșetat care poate fi folosit ca obiect decorativ sau ca obiect de joc. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'c_teddy',
        dimensions: '',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: d_chick,
        name: 'Pătrunjel',
        price: null,
        description: 'Pătrunjel este un pui croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'd_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: e_octopus,
        name: 'Cornelia',
        price: null,
        description: null,
        id: 'e_octopus',
        dimensions: '',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: f_rabbit,
        name: 'Vasile',
        price: null,
        description: null,
        id: 'f_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: g_rabbit,
        name: 'Ion',
        price: null,
        description: null,
        id: 'g_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: h_rabbit,
        name: 'Lăptic',
        price: null,
        description: null,
        id: 'h_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: i_fish,
        name: 'Gheorghe',
        price: null,
        description: null,
        id: 'i_fish',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: j_chick,
        name: 'Brândușa',
        price: null,
        description: null,
        id: 'j_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: k_teddy,
        name: 'Dezbrăcatu',
        price: null,
        description: null,
        id: 'k_teddy',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: l_cat,
        name: 'Bidon',
        price: null,
        description: null,
        id: 'l_cat',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: n_chick,
        name: 'Codruța',
        price: null,
        description: null,
        id: 'n_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: o_rabbit,
        name: 'Mihaela',
        price: null,
        description: null,
        id: 'o_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: p_chick,
        name: 'Mihăiță',
        price: null,
        description: null,
        id: 'p_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: q_rabbit,
        name: 'Gică',
        price: null,
        description: null,
        id: 'q_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: r_rabbit,
        name: 'Nelu',
        price: null,
        description: null,
        id: 'r_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: s_stingray,
        name: 'Mariana',
        price: null,
        description: null,
        id: 's_stingray',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: t_chick,
        name: 'Didina',
        price: null,
        description: null,
        id: 't_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: u_mouse,
        name: 'Florică',
        price: null,
        description: null,
        id: 'u_mouse',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: v_octopus,
        name: 'Lucreția',
        price: null,
        description: null,
        id: 'v_octopus',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: w_cow,
        name: 'Steluța',
        price: null,
        description: null,
        id: 'w_cow',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: x_penguin,
        name: 'Clămpănică',
        price: null,
        description: null,
        id: 'x_penguin',
        dimensions: '',
        tags: ['toys'],
        in_stock: true,
    },
    {
        img: y_octopus,
        name: 'Nectarina',
        price: null,
        description: null,
        id: 'y_octopus',
        dimensions: '',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: z_octopus,
        name: 'Geta',
        price: null,
        description: null,
        id: 'z_octopus',
        dimensions: '',
        tags: ['toys'],
        in_stock: true,
    },
];