import a_frog from './animals/a_frog.webp';
import ab_ghost from './animals/ab_ghost.webp';
import b_bee from './animals/b_bee.webp';
import c_teddy from './animals/c_teddy.webp';
import d_chick from './animals/d_chick.webp';
import e_octopus from './animals/e_octopus.webp';
import f_rabbit from './animals/f_rabbit.webp';
import g_rabbit from './animals/g_rabbit.webp';
import h_rabbit from './animals/h_rabbit.webp';
import i_fish from './animals/i_fish.webp';
import j_chick from './animals/j_chick.webp';
import n_chick from './animals/n_chick.webp';
import o_rabbit from './animals/o_rabbit.webp';
import p_chick from './animals/p_chick.webp';
import q_rabbit from './animals/q_rabbit.webp';
import r_rabbit from './animals/r_rabbit.webp';
import s_stingray from './animals/s_stingray.webp';
import t_chick from './animals/t_chick.webp';
import u_mouse from './animals/u_mouse.webp';
import v_octopus from './animals/v_octopus.webp';
import x_penguin from './animals/x_penguin.webp';
import y_octopus from './animals/y_octopus.webp';
import z_octopus from './animals/z_octopus.webp';
import a_mushroom from './food/a_mushroom.webp';
import b_icecream from './food/b_icecream.webp';
import c_pumpkin from './food/c_pumpkin.webp';
import d_orange from './food/d_orange.webp';
import e_strawberry from './food/e_strawberry.webp';
import f_blueberry from './food/f_blueberry.webp';
import g_blueberry from './food/g_blueberry.webp';
import a_heart from './abstract/a_heart.webp';
import b_moon from './abstract/b_moon.webp';

export const animals = [
    {
        img: d_chick,
        name: 'Pătrunjel',
        price: 70,
        description: 'Pătrunjel este un pui croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'd_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: j_chick,
        name: 'Brândușa',
        price: 70,
        description: 'Brândușa este o găinușă croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'j_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: true,
        is_new: false,
    },
    {
        img: a_frog,
        name: 'Frăguța',
        price: 70,
        description: 'Frăguța este o broscuță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'a_frog',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: b_bee,
        name: 'Bulina',
        price: 70,
        description: 'Bulina este o albinuță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'b_bee',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: c_teddy,
        name: 'Mitică',
        price: 85,
        description: 'Mitică este un ursuleț croșetat care poate fi folosit ca obiect decorativ sau ca obiect de joc. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'c_teddy',
        dimensions: '',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: a_mushroom,
        name: 'Fănica',
        price: 70,
        description: 'Fănica este o ciupercuță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'a_mushroom',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: p_chick,
        name: 'Mihăiță',
        price: 70,
        description: 'Mihăiță este un pui croșetată care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'p_chick',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: true,
    },
    {
        img: n_chick,
        name: 'Codruța',
        price: 40,
        description: 'Codruța este o găinușă croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'n_chick',
        dimensions: '',
        tags: ['toys', 'bag charms', 'keychains'],
        in_stock: true,
    },
    {
        img: e_octopus,
        name: 'Cornelia',
        price: 95,
        description: null,
        id: 'e_octopus',
        description: 'Cornelia este o caracatiță croșetată care poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        tags: ['toys'],
        in_stock: true,
    },
    {
        img: b_icecream,
        name: 'Înghețată',
        price: 80,
        description: 'Înghețata croșetată poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'b_icecream',
        tags: ['toys'],
        in_stock: true,
    },
    {
        img: v_octopus,
        name: 'Lucreția',
        price: 75,
        description: 'Lucreția este o caracatiță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'v_octopus',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: f_rabbit,
        name: 'Vasile',
        price: 70,
        description: 'Vasile este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'f_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: ab_ghost,
        name: 'Mița',
        price: 60,
        description: 'Mița este o fantomiță croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'ab_ghost',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: true,
        is_new: false,
    },
    {
        img: d_orange,
        name: 'Petruța',
        price: 60,
        description: 'Petruța este o portocală croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'd_orange',
        tags: ['toys', 'bag charms'],
        in_stock: true,
        is_new: false,
    },
    {
        img: h_rabbit,
        name: 'Lăptic',
        price: 70,
        description: 'Lăptic este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'h_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: f_blueberry,
        name: 'Mărioara',
        price: 60,
        description: 'Mărioara este o afină croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'f_blueberry',
        tags: ['toys', 'bag charms'],
        in_stock: true,
    },
    {
        img: g_blueberry,
        name: 'Mădălina',
        price: 60,
        description: 'Mădălina este o afină croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'g_blueberry',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: o_rabbit,
        name: 'Mihaela',
        price: 70,
        description: 'Mihaela este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'o_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: q_rabbit,
        name: 'Gică',
        price: 70,
        description: 'Gică este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'q_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: r_rabbit,
        name: 'Nelu',
        price: 70,
        description: 'Nelu este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'r_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: g_rabbit,
        name: 'Ion',
        price: 70,
        description: 'Ion este un iepuraș croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'g_rabbit',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: s_stingray,
        name: 'Mariana',
        price: 65,
        description: 'Mariana este o pisică de mare croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 's_stingray',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: t_chick,
        name: 'Didina',
        price: 40,
        description: 'Didina este o găinușă croșetată care poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 't_chick',
        dimensions: '',
        tags: ['toys', 'bag charms', 'keychains'],
        in_stock: true,
    },
    {
        img: u_mouse,
        name: 'Florică',
        price: 70,
        description: 'Florică este un șoricel croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'u_mouse',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: true,
    },
    {
        img: x_penguin,
        name: 'Clămpănică',
        price: 95,
        description: 'Clămpănică este un pinguin croșetat care poate fi folosit ca obiect decorativ sau ca obiect de joc. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'x_penguin',
        dimensions: '',
        tags: ['toys'],
        in_stock: true,
    },
    {
        img: y_octopus,
        name: 'Nectarina',
        price: 95,
        description: 'Nectarina este o caracatiță croșetată care poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'y_octopus',
        dimensions: '',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: z_octopus,
        name: 'Geta',
        price: 95,
        description: 'Geta este o caracatiță croșetată care poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'z_octopus',
        dimensions: '',
        tags: ['toys'],
        in_stock: true,
    },
    {
        img: c_pumpkin,
        name: 'Dovleac',
        price: 80,
        description: 'Dovleacul croșetat poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'c_pumpkin',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: e_strawberry,
        name: 'Căpșunică',
        price: 60,
        description: 'Căpșunica croșetată poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'e_strawberry',
        tags: ['toys', 'bag charms'],
        in_stock: true,
    },
    {
        img: a_heart,
        name: 'Inimioară',
        price: 90,
        description: 'Inimioara croșetată poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'a_heart',
        tags: ['toys'],
        in_stock: false,
    },
    {
        img: b_moon,
        name: 'Lună',
        price: 70,
        description: 'Luna croșetată poate fi folosită ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'b_moon',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    {
        img: i_fish,
        name: 'Gheorghe',
        price: 50,
        description: 'Gheorghe este un pește croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
        id: 'i_fish',
        dimensions: '',
        tags: ['toys', 'bag charms'],
        in_stock: false,
    },
    // {
    //     img: c_pikachu,
    //     name: 'Pikachu',
    //     price: 50,
    //     description: 'Pikachu este un pokemon croșetat care poate fi folosit ca obiect decorativ sau ca obiect de joc. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
    //     id: 'c_pikachu',
    //     tags: ['toys'],
    //     in_stock: true,
    // },
    // {
    //     img: k_teddy,
    //     name: 'Dezbrăcatu',
    //     price: 50,
    //     description: 'Dezbrăcatu este un ursuleț croșetat care poate fi folosit ca obiect decorativ, ca obiect de joc sau ca accesoriu pentru geantă. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
    //     id: 'k_teddy',
    //     dimensions: '',
    //     tags: ['toys', 'bag charms'],
    //     in_stock: false,
    // },
    // {
    //     img: l_cat,
    //     name: 'Bidon',
    //     price: 50,
    //     description: 'Bidon este un motan croșetat care poate fi folosit ca obiect decorativ sau ca obiect de joc. Este confecționat dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
    //     id: 'l_cat',
    //     dimensions: '',
    //     tags: ['toys', 'bag charms'],
    //     in_stock: false,
    // },
    // {
    //     img: w_cow,
    //     name: 'Steluța',
    //     price: 50,
    //     description: 'Steluța este o văcuță croșetată care poate fi folosită ca obiect decorativ sau ca obiect de joc. Este confecționată dintr-un fir antialergenic plușat, catifelat, moale și plăcut la atingere. Umplutura este hipoalergenică, își păstrează forma și volumul, asigurând un sentiment plăcut la atingere și siguranță pentru utilizator.',
    //     id: 'w_cow',
    //     dimensions: '',
    //     tags: ['toys', 'bag charms'],
    //     in_stock: false,
    // },
];